FROM ghcr.io/astral-sh/uv:0.11.16-python3.14-trixie@sha256:244c325aaa0c2474445996cdac081cd3af9bab8fbd31a27577cb27e80c682daa AS builder
WORKDIR /app
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project --group race

FROM python:3.14-slim-trixie@sha256:7d8de339aa8619f9b25e7d474d687ae4f6ef9704adad90a136af0f485adeccb7
WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"
COPY laps.py .
ENTRYPOINT ["python", "laps.py"]
