FROM python@sha256:46cb7cc2877e60fbd5e21a9ae6115c30ace7a077b9f8772da879e4590c18c2e3 AS builder # 3.12-slim (3.12.13)
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
COPY pi-requirements.txt .
RUN pip install --no-cache-dir --root-user-action=ignore --prefix=/install -r pi-requirements.txt

FROM python@sha256:46cb7cc2877e60fbd5e21a9ae6115c30ace7a077b9f8772da879e4590c18c2e3 # 3.12-slim (3.12.13)
WORKDIR /app
COPY --from=builder /install /usr/local
COPY telem.py pisugar-monitor.py ./
