FROM ghcr.io/astral-sh/uv:0.11.13-python3.14-trixie@sha256:8cc52137ffba0e08e8519f299e85c0ec4ed6c2ff8476e740bf32686bcb530fbd
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --group pi
COPY telem.py pisugar-monitor.py ./
