FROM ghcr.io/astral-sh/uv:0.11.16-python3.14-trixie@sha256:9c56cda4825e06df86b0fa03bfdd7060d2b4529682317ae2647c337df4fb23e7
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --group race
COPY laps.py .
ENTRYPOINT ["python", "laps.py"]
