# python:3.12-slim (3.12.13)
FROM python@sha256:0ba001803c72c128063cfa88863755f905cefabe73c026c66a5a86d8f1d63e98
WORKDIR /app
COPY race-requirements.txt .
RUN pip install --no-cache-dir --root-user-action=ignore -r race-requirements.txt
COPY laps.py .
ENTRYPOINT ["python", "laps.py"]
