services:
  telem:
    image: ghcr.io/wot-lemons/lemongrass:${TAG:-latest}
    command: python telem.py
    restart: always
    devices:
      - /dev/obd:/dev/obd
    volumes:
      - /home/pi/.influxcred:/home/pi/.influxcred:ro

  pisugar-monitor:
    image: ghcr.io/wot-lemons/lemongrass:${TAG:-latest}
    command: python pisugar-monitor.py
    restart: always
    network_mode: host
    volumes:
      - /home/pi/.influxcred:/home/pi/.influxcred:ro
