name: Check Requirements

on:
  pull_request:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Verify requirements files are up to date
        run: |
          uv export --group pi --no-hashes --frozen --no-header | diff - pi-requirements.txt
          uv export --group race --no-hashes --frozen --no-header | diff - race-requirements.txt
