name: Python Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'Dockerfile.laps'
      - 'Dockerfile.pi'
      - 'pi-requirements.txt'
      - 'race-requirements.txt'
      - 'uv.lock'

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run tests
        run: uv run --with pytest pytest tests/
