name: Python Syntax Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  syntax:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Check syntax and style
        run: uv run --with ruff ruff check .
