name: Python Syntax Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  syntax:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.3"

      - name: Check syntax and style
        run: uv run ruff check .
